### ISSUE TITLE
https://github.com/BFEdev/BFE.dev-solutions/blob/main/problem/undefined-to-null_en.md New Better Readability Solution

### ISSUE THREAD

**Issue by rajas2716** [BFEdev/BFE.dev-solutions#73]
function undefinedToNull(arg) {
    // your code here
    for(let key in arg){
      if(typeof arg[key] === "object"){
        undefinedToNull(arg[key])
      }
      else if(arg[key] == undefined){
        arg[key] = null
      }
    }
  }

This solution passes all the test cases and also is more readable and concise than the official solution. It also does not use any fancy keywords which can be hard for a beginner to understand.

**Comment by BFEdev** [comment]
please create PR rather than issue.
